global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Product-Service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9092']  # Use this when Spring Boot runs locally
